version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
